---
configurations:
  # Foaier
  ap-cf-f-l:
    config: archer-c5
    ip: 10.20.0.50
    wlans:
      0:
        bssid: 02:00:0f:20:10:00
        channel: 106
      1:
        bssid: 02:00:0f:20:10:01
        channel: 13
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-cf-f-r:
    config: archer-c5
    ip: 10.20.0.51
    wlans:
      0:
        bssid: 02:00:0f:20:10:10
        channel: 58
      1:
        bssid: 02:00:0f:20:10:11
        channel: 5
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  # Main room
  ap-cf-mr-1:
    config: dap2965
    ip: 10.20.0.52
    wlans:
      0:
        bssid: 02:00:0f:20:20:00
        channel: 122
      1:
        bssid: 02:00:0f:20:20:01
        channel: 5
    mixins:
      - all
      - dap2965
      - dap2965-single-trunk
  ap-cf-mr-2:
    config: dap2965
    ip: 10.20.0.53
    wlans:
      0:
        bssid: 02:00:0f:20:20:10
        channel: 42
      1:
        bssid: 02:00:0f:20:20:11
        channel: 1
    mixins:
      - all
      - dap2965
      - dap2965-single-trunk
  ap-cf-mr-3:
    config: linksys
    ip: 10.20.0.54
    wlans:
      0:
        bssid: 02:00:0f:20:20:20
        channel: 106
      1:
        bssid: 02:00:0f:20:20:21
        channel: 9
    mixins:
      - all
      - linksys
      - linksys-single-trunk
  ap-cf-mr-4:
    config: dap2965
    ip: 10.20.0.55
    wlans:
      0:
        bssid: 02:00:0f:20:20:30
        channel: 58
      1:
        bssid: 02:00:0f:20:20:31
        channel: 13
    mixins:
      - all
      - linksys
      - linksys-single-trunk
  # Small room
  ap-cf-sr-1:
    config: archer-c5
    ip: 10.20.0.56
    wlans:
      0:
        bssid: 02:00:0f:20:30:00
        channel: 42
      1:
        bssid: 02:00:0f:20:30:01
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-cf-sr-2:
    config: archer-c7
    ip: 10.20.0.57
    wlans:
      0:
        bssid: 02:00:0f:20:30:10
        channel: 58
      1:
        bssid: 02:00:0f:20:30:11
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  # Chillout area and quiet workshops
  ap-cf-ch:
    config: archer-c5
    ip: 10.20.0.58
    wlans:
      0:
        bssid: 02:00:0f:20:40:00
        channel: 42
      1:
        bssid: 02:00:0f:20:40:01
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-cf-qws:
    config: archer-c5
    ip: 10.20.0.59
    wlans:
      0:
        bssid: 02:00:0f:20:40:10
        channel: 42
      1:
        bssid: 02:00:0f:20:40:11
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  # Workshops and overflow
  ap-ws-ws1:
    config: linksys
    ip: 10.20.0.60
    wlans:
      0:
        bssid: 02:00:0f:20:50:00
        channel: 42
      1:
        bssid: 02:00:0f:20:50:01
        channel: 9
    mixins:
      - all
      - linksys
      - linksys-single-trunk
  ap-ws-ws2:
    config: archer-c5
    ip: 10.20.0.61
    wlans:
      0:
        bssid: 02:00:0f:20:50:10
        channel: 106
      1:
        bssid: 02:00:0f:20:50:11
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  # NOC/Team room
  ap-ws-noc:
    config: archer-c5
    ip: 10.20.0.62
    wlans:
      0:
        bssid: 02:00:0f:20:50:20
        channel: 106
      1:
        bssid: 02:00:0f:20:50:21
        channel: 13
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
