---
configurations:
  ap-cf-sr-2:
    config: archer-c5
    ip: 10.20.0.57
    wlans:
      0:
        bssid: 18:d6:c7:fc:ed:37
        channel: 60
      1:
        bssid: 18:d6:c7:fc:ed:38
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
